version: '3.3'

services:
   andaluh-wiki:
     image: andaluh/wiki:v1
     container_name: andaluh_wiki
     restart: always
     build: .
     ports:
       - "5001:80"
     environment:
       - GA_TRACK_UA=REPLACE_WITH_YOURS_OR_REMOVE # Adjust your Google Analytics ID (analytics.google.com)
       - DISALLOW_ROBOTS=SET_TRUE_OR_REMOVE # When this variable is set, robots.txt file disallow indexing.