name: Push to Container Registry

on:
  push:
      branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_NAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t ${{ secrets.REGISTRY_NAME }}/andaluh_wiki:latest
        docker push ${{ secrets.REGISTRY_NAME }}/andaluh_wiki:latest
